name: Unit Tests

on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: "Ruby: ${{ matrix.ruby }} OS: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
        # 3.0 is interpreted as 3
        ruby: [2.6, 2.7, "3.0", 3.1, 3.2, 3.3]
        exclude:
          - { os: windows-2019, ruby: 2.2 }
          - { os: windows-2019, ruby: 2.3 }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ruby & 'bundle install'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Test
        run: |
          ruby -v
          bundle exec rake
        env:
          CI: true
